### ISSUE TITLE
submenu

### ISSUE THREAD

**Issue by UziTech** [andremov/atom-themed-context-menu#1]
This package looks amazing! but it is missing submenus.

**Comment by andremov** [comment]
Hey! 

Thank you for bringing this to my attention. I'm on it.

**Comment by UziTech** [comment]
Now it looks like there is something going on with the `keyboard_arrow_right`. Not sure if that is just my computer.

![image](https://user-images.githubusercontent.com/97994/109762469-3f3a9400-7bb6-11eb-92d7-c7b846d98b91.png)

**Comment by UziTech** [comment]
It seems like it might be because I don't have the `Material Icons` font installed.

**Comment by UziTech** [comment]
Maybe it should use octicons since they are always included in Atom

```css
content: '\f078';
font-family: 'Octicons Regular';
```

**Comment by andremov** [comment]
> Maybe it should use octicons since they are always included in Atom
> 
> ```css
> content: '\f078';
> font-family: 'Octicons Regular';
> ```

Applied this change in v0.2.1, should work. Sorry for the inconvenience.

**Comment by UziTech** [comment]
Thanks for the fast response. It works great now.
