### ISSUE TITLE
Question on your title bar in screenshot

### ISSUE THREAD

**Issue by femto-code** [andremov/atom-themed-context-menu#12]
Hi, I installed your great plugin and additionally want to have the title bar style like yours in the screenshot in your readme. I mean the hidden default title bar and the look which is more in line with theme.

Which package did you use to accomplish this? Thank you!

**Comment by andremov** [comment]
Hey, glad to hear you like the plugin.

The package I use for the title bar is this: https://atom.io/packages/title-bar-replacer
