### ISSUE TITLE
Not focussed if invoked by keyboard

### ISSUE THREAD

**Issue by 73** [andremov/atom-themed-context-menu#13]
Hi,

thanks for this extension. However, I might have found a bug.

## Steps to reproduce
1. Invoke the context menu with the `menu key` on the keyboard.
2. Press `down arrow`.

## Expectation
The first entry should be selected.

## What actually happens
The context menu has no focus. The arrow still moves the cursor in the editor. The user in unable to select an entry with the keyboard.

**Comment by andremov** [comment]
Hey! Thanks for the issue. Should be fixed in newest version.
