### ISSUE TITLE
Menu is cut off at window border

### ISSUE THREAD

**Issue by 73** [andremov/atom-themed-context-menu#8]
![image](https://user-images.githubusercontent.com/529346/111030761-540ff680-8404-11eb-80c4-aad4be95753d.png)

**Comment by andremov** [comment]
while the screenshot shows the problem very clearly, i am curious as to the position of the mouse when you right clicked

**Comment by andremov** [comment]
thanks for the feedback

**Comment by 73** [comment]
The current version does not show the menu at all for me. But does not emit an error. Context menus just stopped working.

**Comment by andremov** [comment]
dist was rebuilt , should be working now

**Comment by 73** [comment]
I am afraid it does not for me. Context menu is not shown on right click.

**Comment by 73** [comment]
I am not using this anymore. However, your extension made me so annoyed by the bright context menu that I ran a more drastic approach.  Work on linux:
### 1. Copy desktop to local folder.
```sh
cp /usr/share/applications/atom.desktop ~/.local/share/applications/atom.desktop 
```

### 2. Set environment
Make the line in the file look lie this:
```diff
- Exec=env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom %F
+ Exec=env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false GTK_THEME=Adwaita:dark /usr/bin/atom %F
```

### 3. Fix the terminal command
```sh
echo 'alias atom="GTK_THEME=Adwaita:dark atom"' >> ~/.profile
```

### Enjoy darkness
